version: '3'
services:
  mongo:
    image: mongo
    container_name: cardtracker-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
    build: .
    container_name: cardtracker-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/cardtracker
    depends_on:
      - mongo
